### ISSUE TITLE
BB-18: Add GrB_ONE unary operator

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#8]
f(x) = 1

**Comment by tgmattso** [comment]
Why do we need this?  I need an example where this would be useful.  I don't want to fall into the trap of adding stuff just because we can and it would make the spec more complete.  If we make GraphBLAS too complex for people to understand, they will respond by ignoring it.

**Comment by DrTimothyAldenDavis** [comment]
This is useful for replacing all entries in a matrix with a single value, 1, as in the MATLAB C =spones (A).  I need it for MATLAB.

However, with my new iso feature, I can also do this with C{C}=1, with a call to 

GrB_assign (C, C, NULL, 1, GrB_ALL, nrows, GrB_ALL, ncols, GrB_DESC_S).

however, operators that return "1" are powerful.  I have many use cases for the binary op version of this, f(x,y)=1.  That operator is absolutely essential for best performance of the GAP benchmarks.

Computing the row degree (# of entries in each row of a matrix) canbe done very quickly with the following.  Say A is m-by-n.

GrB_Vector_new (&x, anytype, n) ;
GrB_assign (x, NULL, NULL, 1, GrB_ALL, n, NULL) ; // set all entries of x to 1; x is now "iso".  This takes O(1) time and space.
GrB_Vector_new (&d, GrB_INT64, m) ;
GrB_mxv (d, NULL, NULL, GxB_PLUS_PAIR_INT64, A, x, NULL) ;

Assuming A is held by row (my default), the above computation takes a total time O(k) where k < m.  This time taken does *not* depend on nvals(A).  It is far faster than that.

THe PLUS_PAIR semiring just counts the intersection of two vectors, so that d(i) = # of entries in the intersection of A(i,:) and x.  HOwever, since I know that x is entirely full, with all entries present, I know that d(i) = # of entries in A(i,:).  But I have that already in my internal data structure, so I compute d(i) in O(1) time.  I can only play this trick with the PLUS_PAIR semiring, and I cannot do it with any other multiply operator.

PAIR, as f(x,y)=1, is absurdly simple to add to the spec, and it provides astonishing increases in performance for so many many things like this.

The ANY_PAIR operator is superbly important.  It says "just compute the pattern of C, for C = A*B, and the result is iso-valued with every entry present in the pattern of C equal to 1".  MIN_PAIR says the same thing, actually.  Because PAIR always produces the result of 1, I know for certain that any value computed by MIN_PAIR is equal to 1.  All I thus need to compute is the pattern of C.  Its values are all known, and equal to 1.  I have thus computed C as a "GrB_PATTERN" matrix without the awful need for adding GrB_PATTERN to the spec.

**Comment by DrTimothyAldenDavis** [comment]
We can close this issue.  A unary GrB_ONE_T operator is not that important, now that I can do the same thing with GrB_assign from scalar, and a structural mask  

The binary operator f(x,y)=1 is VERY important (#46).  It should be added (call it GrB_PAIR_T, or GrB_ONE_T if you like).
