### ISSUE TITLE
BB-21: BinaryOps RMINUS and RDIV

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#9]
RMINUS: f(x, y) = y - x
RDIV: f(x, y) = y/x

**Comment by mcmillan03** [comment]
Why can't the user just call MINUS or DIV by reversing the order of the input operands?

**Comment by DrTimothyAldenDavis** [comment]
For eWise operators, that is simple to do.  It cannot be done inside a semiring.  Internally I sometimes replace things like C=A'*B' with C = (B*A)'.  To do so, I have to "flip" the operator.  If the multiply operator is MINUS, say, I have to replace it with RMINUS.

**Comment by DrTimothyAldenDavis** [comment]
This can be closed.  The operators are important internally, when I need to "flip" an operator, but the are not so useful to expose to the user application.

A similar case occurs in the GrB_IndexUnaryOps.  All of the operators that are not commutative appear in pairs (with i and j reversed) with one exception: GrB_DIAGINDEX_*.  So internally, I need a GxB_FLIPDIAGINDEX_* that reverses the roles of i and j.  However, I do not expose this operator to the user.

The same can be said for RMINUS and RDIV.  They don't need to be exposed to the user.  I won't remove my GxB_RMINUS* and GxB_RDIV*, since that would break backward compatibility, but they do not need to be added to the spec.
